# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean"
license = "MIT"
licenselink = "https://github.com/akccakcctw/clean/blob/master/LICENSE.md"
description = "A clean blog theme for hugo"
homepage = "https://github.com/akccakcctw/clean"
tags = ["blog"]
features = ["html5", "css3"]
min_version = "0.20.5"

[author]
  name = "akccakcctw"
  homepage = "https://rex-tsou.com"
