name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          npx
          -p @semantic-release/changelog
          -p @semantic-release/git
          -p @semantic-release/github
          -p @semantic-release/release-notes-generator
          -p semantic-release-slack-bot
          -p semantic-release
          semantic-release
